# Tensorflow 문법 기초
## tf.<span class="mark">constant</span>와 tf.<span class="mark">Session</span>에 대한 학습

## Tensorflow는 Define & Run 방식이다.
![1](https://i.imgur.com/XFKVIJT.png)

## 1. Tensorflow 사용

In [2]:
import tensorflow as tf

C:\Users\infoe\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


tensorflow를 import 합니다. tensorflow를 import 할 때에는 tf로 이름을 만들어 줍니다. <br>
참고로, tensor는 N-dimensional array를 뜻합니다.

In [2]:
print(tf.__version__)

1.4.0


tensorflow 버전을 확인할 때 tf.__version__을 사용합니다.

## 2. Hello World

In [4]:
hello = tf.constant("Hello ")
world = tf.constant("World")

어떤 언어든지 가장 먼저 해보는 Hello World를 출력해보도록 하겠습니다.
먼저 가장 기초적인 tensor인 constant를 이용하여 Hello와 World를 만들어 보도록 하겠습니다.
Hello constant는 "Hello"를, World constant는 "World"를 저장합니다.

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

hello의 타입을 살펴보면 String이 아니라 Tensor 입니다. 즉, Tensor Object 입니다. 

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


hello 변수를 print를 이용하여 출력해 보면 String이 출력되는 것이 아니라 <span class="mark">Tensor Object가 출력</span>이 됩니다.<br>
Tensor Object 내부를 보면 Const, Shape 그리고 Tensor 의 data type = String인 것을 알 수 있습니다.

In [12]:
with tf.Session() as sess:
    result = sess.run(hello + world)   

hello를 출력하기 위해서는 session 내부에서 연산을 해야 합니다. <br>
Session을 사용하기 위해서는 tf.Session()을 사용해야 합니다. <br>
여기서 with를 사용하는 이유는 Session을 Open 하였을 때, 마지막에 Close를 따로 선언하지 않기 위함입니다. With 가 끝나게 되었을 때 Session은 자동적으로 Close 됩니다. <br>
Session 내부 함수로 <span class="mark">run을 이용</span>하면 <span class="mark">Tensor에 대한 연산을 실행</span>할 수 있습니다.

In [13]:
print(result)

b'Hello World'


Tensor 자체를 Print한 경우에는 Tensor에 대한 정보가 출력 되었지만, tf.Session의 run 함수를 이용하여 Tensor에 대한 연산 결과를 출력하면 Tensor Data Type = String이므로 문자열이 출력 되었습니다. 이 때 접두사 b는 Python3 문법에 따라 bytes literal 이 표시되었습니다.

## 3. 더하기 연산

In [7]:
a = tf.constant(10)
b = tf.constant(20)

다음으로 Tensor Object를 이용하여 + 연산을 해보도록 하겠습니다.
앞에서 hello와 world 변수를 선언한 것 처럼 a와 b 변수를 선언해 보도록 하겠습니다. <br>
변수 a에는 10을, 변수 b에는 20을 할당하였습니다.

In [8]:
type(a)

tensorflow.python.framework.ops.Tensor

변수 a의 타입은 hello와 같이 Tensor 입니다.

In [9]:
a + b

<tf.Tensor 'add:0' shape=() dtype=int32>

hello 변수 자체를 print 한 것과 같이 a + b의 결과 또한 Tensor 이고 Tensor의 결과 add, shape, data type과 같은 내용이 출력 됩니다.

In [10]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

다시 한번 더 a + b 연산을 하면 Tensor의 결과는 add_2가 됩니다. tensorflow가 background에서 연산에 대한 numbering을 하고 있음을 알 수 있습니다.<br>
하지만, 명심해야 할 것은 아직 Session 내부에서 연산이 수행된 것이 아니므로 실제 더하기 연산이 적용된 것은 아닙니다.

In [11]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [12]:
print(result)

30


앞에서 "Hello World"를 출력하는 방식과 마찬가지로 Session 내부 함수를 이용하여 Tensor에 연산을 실제 적용하면 덧셈 연산을 구현할 수 있습니다.

## 4. NumPy 연산과 비슷한 Tensorflow 연산

In [4]:
const = tf.constant(10)

tf.constant를 이용하여 임의의 상수를 생성합니다.

In [6]:
fill_mat = tf.fill((4, 4), 10)

tf.fill 함수를 이용하여 (4, 4) dimension에 10의 값을 가지는 matrix를 생성합니다.

In [8]:
myzeros = tf.zeros((4,4))

tf.zeros를 이용하여 (4, 4) dimension의 0-matrix를 생성합니다.

In [9]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

tf.random_normal을 이용하여 (4, 4) dimension의 normal distribution의 matrix를 생성합니다.
mean과 stddev 값은 기본값으로 각각 0과 1.0인 standard normal distribution을 가지고 있으나 mean과 stddev를 변경할 수 있습니다.

In [10]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

tf.random_uniform을 이용하여 (4, 4) dimension의 uniform distribution을 가지고 minval과 maxval을 설정할 수 있습니다.

In [26]:
my_ops = [const, fill_mat, myzeros, myrandn, myrandu]

앞에서 선언한 변수들을 list를 이용하여 묶어줍니다.

In [17]:
sess = tf.InteractiveSession()

간단하게 연산 결과를 확인하기 위하여 Session 대신 InteractiveSession을 선언하였습니다. <br>
함수명과 같이 Interactive 하게 사용가능하고 Tensor.eval(), Operation.run()을 이용하여 연산이 가능합니다. <br>
tf.InteractiveSession()을 사용하면 일반 ide 처럼 중간과정을 처리합니다.<br>
하지만, 향후 사용할 방식은 with 구문과 tf.Session()을 이용한 형태입니다.

In [32]:
for op in my_ops:
    print(op)
    print(sess.run(op)) # print(op.eval()) 사용 가능 (InteractiveSession이 선언되었기 때문)
    print('\n')

Tensor("Const_5:0", shape=(), dtype=int32)
10


Tensor("Fill:0", shape=(4, 4), dtype=int32)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


Tensor("zeros:0", shape=(4, 4), dtype=float32)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Tensor("random_normal_1:0", shape=(4, 4), dtype=float32)
[[-0.86932355 -0.62501574  0.46983108 -0.7334518 ]
 [ 0.95767033 -0.03435803  0.13224508  1.2445968 ]
 [ 0.92577076 -0.16110788  0.9361842   0.62049663]
 [-1.1582403   0.00323756 -0.20112082 -0.56624585]]


Tensor("random_uniform:0", shape=(4, 4), dtype=float32)
[[0.3905195  0.03458261 0.8546864  0.80481124]
 [0.24862123 0.29332435 0.37042022 0.07679212]
 [0.85840297 0.4314307  0.45534062 0.5187558 ]
 [0.4722339  0.9884018  0.53234255 0.3311721 ]]




반복문을 이용하여 Tensor의 정보와 값을 출력 하였습니다.

## 5. Matrix Multiplication

In [12]:
a = tf.constant([ [1, 2],
                  [3, 4] ])

변수 a에 tf.constant를 이용하여 2 x 2 matrix를 선언하였습니다.<br>
시각적으로 matrix 처럼 보이게 표현하였지만 사실 2중으로 표현한 list에 해당합니다.

In [13]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

변수 a는 Tensor Object 이고 a의 shape를 확인해 보면 Dimension(2), Dimension(2)로 2 x 2 matrix임을 확인할 수 있습니다.

In [14]:
b =  tf.constant([ [10], [100] ])

변수 b에 tf.constant를 이용하여 2 x 1 matrix를 선언하였습니다. 

In [15]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

b의 shape을 확인해 보면 Dimension(2), Dimension(1)로 2 x 1 matrix 임을 확인할 수 있습니다.

In [18]:
result = tf.matmul(a, b)
sess.run(result)

array([[210],
       [430]])

matrix a의 shape은 2 x 2이고 matrix b의 shape은 2 x 1 이므로 matrix multiplication 시 2 x 1 matrix를 얻을 수 있습니다.

In [19]:
result.get_shape()

TensorShape([Dimension(2), Dimension(1)])

result의 shape은 2 x 1 입니다.

In [20]:
result.eval()

array([[210],
       [430]])

앞에서도 설명한 바와 같이 InteractiveSession()을 한번 선언하면 Tensor.eval()을 통하여 연산 결과를 확인할 수 있습니다.